### ISSUE TITLE
Python setup.py install  ERROR!!!

### ISSUE THREAD

**Issue by Yang-Tui** [phasegenomics/hic_qc#53]
Hi,
I have the same question about the install step, but the questioner didn't update on last issue, maybe he solved the question? So I create a new issue.
We used conda to create env to installation just following README.

```
git clone https://github.com/phasegenomics/hic_qc.git
cd hic_qc/
conda env create -n hic_qc --file env.yml
conda activate hic_qc
python setup.py install --user
```
But it failed at the last step `setup.py`install, below is the wrong message 

And we checked  the files were all exsit in the hic_qc file without anything missing. 

```

(hic_qc) [crlee@h71 hic_qc]$ python setup.py
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    version=versioneer.get_version(),
  File "/home/hpc/crlee/softwares/hic_qc/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
  File "/home/hpc/crlee/softwares/hic_qc/versioneer.py", line 1453, in get_versions
    pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
  File "/home/hpc/crlee/softwares/hic_qc/versioneer.py", line 1110, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
Could anyone help me about this? Thank you so much.

**Comment by bnelsj** [comment]
Can you tell us which version of git you are using? It might be out of date.

**Comment by Yang-Tui** [comment]
Thanks for reply,

Our git version is 1.7.1

If it is out of date, we will update it and retry.
